version: '3.3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_DATABASE=app
      - MARIADB_ROOT_PASSWORD=root
    networks:
      - default
    volumes:
      - db-vol:/var/lib/mysql3   
  myapp:
    image: docker.io/bitnami/laravel:8
    ports:
      - '8000:8000'
    volumes:
      - './project:/app'
    depends_on:
      - mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - MARIADB_ROOT_USER=root
      - MARIADB_DATABASE=app
      - MARIADB_ROOT_PASSWORD=root
    depends_on:
      - mariadb
    ports:
      - 8181:80
    networks:
      - default

volumes:
  db-vol: